apiVersion: v1
kind: Pod
metadata:
  name: secure-hostpath-replacement
  namespace: audit-zone
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /data
          name: data-volume
      securityContext:
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        runAsUser: 1000
        capabilities:
          drop: ["ALL"]
  volumes:
    - name: data-volume
      emptyDir: {}