apiVersion: v1
kind: Pod
metadata:
  name: secure-nonroot
  namespace: audit-zone
spec:
  containers:
    - name: nginx
      image: nginx
      securityContext:
        runAsNonRoot: true
        readOnlyRootFilesystem: true
        runAsUser: 1000
        capabilities:
          drop: ["ALL"]